move_group_name: wx250s_arm
planning_frame: base_link
robot_link_command_frame: base_link
ee_frame_name: wrist_link

# Incoming commands
command_in_type: speed_units
scale:
  linear: 0.1
  rotational: 0.3
  joint: 0.5

# Outgoing commands
command_out_type: trajectory_msgs/JointTrajectory
command_out_topic: /wx250s_arm_controller/joint_trajectory
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

# Timing
publish_period: 0.01
incoming_command_timeout: 0.1

# Topics
cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_states
status_topic: ~/status

# Singularity handling (USE DEMO VALUES)
lower_singularity_threshold: 17.0
hard_stop_singularity_threshold: 30.0
leaving_singularity_threshold_multiplier: 2.0
joint_limit_margin: 0.1

# Collision checking
check_collisions: true
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02
