ekf_filter_node:
  ros__parameters:
    frequency: 50.0                # EKF update rate
    sensor_timeout: 0.5
    two_d_mode: true               # we assume planar robot
    transform_time_offset: 0.0
    print_diagnostics: true
    # Frames
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    # Inputs (names of topics)
    odom0: /odom                   # fake_odom publishes /odom
    imu0: /imu/data_raw
    # Use odom and imu (select which vars are used from each sensor)
    # odom0_config: (x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw) booleans
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true]
    # imu0_config: use angular velocities (yaw rate) and linear acc to help orientation/ank
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    # Covariances - tune if needed
    odom0_covariance: [0.05, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0]
    imu0_covariance: [0.02, 0, 0, 0, 0, 0, 0.04, 0, 0, 0, 0, 0, 0, 0, 0]

    publish_tf: true                # EKF will broadcast odom -> base_link
    publish_acceleration: false
