slam_toolbox:
  ros__parameters:

    mode: mapping

    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # Inputs
    scan_topic: /scan
    use_imu: true
    imu_topic: /imu/data
    use_odometry: false

    # IMU settings
    imu_frame: imu_link

    # Mapping
    resolution: 0.05
    max_laser_range: 12.0

    # Motion thresholds
    minimum_travel_distance: 0.03
    minimum_travel_heading: 0.03

    map_update_interval: 1.0
    scan_buffer_size: 10
    