controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # arm_position_controller:
    #   type: position_controllers/JointGroupPositionController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - elbow_joint
      - wrist_joint


    # The controller will expect position commands as input for each of these joints.
    command_interfaces:
      - position

    # Tells the controller that it should expect to receive position data as the state
    # feedback from the hardware interface.
    state_interfaces:
      - position

    # If true, When set to true, the controller will not use any feedback from the system
    # (e.g., joint positions, velocities, efforts) to compute the control commands.
    open_loop_control: false

    # When set to true, it allows the controller to integrate the trajectory goals it receives.
    # This means that if the goal trajectory only specifies positions, the controller will
    # numerically integrate the positions to compute the velocities and accelerations required
    # to follow the trajectory.
    allow_integration_in_goal_trajectories: true

    # Allow non-zero velocity at the end of the trajectory
    allow_nonzero_velocity_at_trajectory_end: false


diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["FWLJ"]
    right_wheel_names: ["FWRJ"]

    wheel_separation: 0.40
    wheel_radius: 0.08

    base_frame_id: ebot_base_link
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

# controller_manager:
#   ros__parameters:
#     update_rate: 100

#     arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
    
    

# arm_controller:
#   ros__parameters:
#     joints:
#       - base_rotation_joint
#       - shoulder_joint
#       - elbow_joint
#       - wrist_joint
#       - wrist_roll_joint

#     command_interfaces:
#       - position

#     state_interfaces:
#       - position
#       - velocity

#     allow_partial_joints_goal: false
