controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["FWLJ"]
    right_wheel_names: ["FWRJ"]

    wheel_separation: 0.40
    wheel_radius: 0.08

    base_frame_id: ebot_base
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0
