# Default initial positions for ebot's ros2_control fake system

initial_positions:
  arm_gripper_left_joint: 0
  arm_joint1: 0
  arm_joint2: 0
  arm_joint3: 0
  arm_joint4: 0
  arm_wrist_roll_joint: 0